name = "New Russian Language Pack"
version = "0.1.2"
local desc = {
	en = "Russian localization \n\nVersion: "..version,
	ru = "\nРусификация игры \nВерсия: "..version}
description = language and desc[language] or desc["en"]
author = "Some1, alevastor, FBNikita, Graph"
forumthread = ""
api_version = 10
icon_atlas = "modicon.xml"
icon = "modicon.tex"
priority = 1
dont_starve_compatible = true
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
server_filter_tags = {"russian"}
